[package]
name = "falling-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9"
bevy_egui = "0.17"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
wasm-bindgen = "0.2.83"
crossbeam = "0.8.2"

[dependencies.web-sys]
version = "0.3.60"
features = ['Window']
